/**
 * ModredIP ABI subset used by the frontend (same as App.tsx CASAMIGOS_ABI).
 * Used by test scripts to call the contract.
 */
export const MODRED_IP_ABI = [
  {
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "getIPAsset",
    outputs: [
      { name: "owner", type: "address" },
      { name: "ipHash", type: "string" },
      { name: "metadata", type: "string" },
      { name: "isEncrypted", type: "bool" },
      { name: "isDisputed", type: "bool" },
      { name: "registrationDate", type: "uint256" },
      { name: "totalRevenue", type: "uint256" },
      { name: "royaltyTokens", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "licenseId", type: "uint256" }],
    name: "getLicense",
    outputs: [
      { name: "licensee", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "royaltyPercentage", type: "uint256" },
      { name: "duration", type: "uint256" },
      { name: "startDate", type: "uint256" },
      { name: "isActive", type: "bool" },
      { name: "commercialUse", type: "bool" },
      { name: "terms", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "tokenId", type: "uint256" }, { name: "claimant", type: "address" }],
    name: "getRoyaltyInfo",
    outputs: [
      { name: "totalRevenue", type: "uint256" },
      { name: "claimableAmount", type: "uint256" },
      { name: "lastClaimed", type: "uint256" },
      { name: "totalAccumulated", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "nextTokenId", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "nextLicenseId", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ name: "ipHash", type: "string" }, { name: "metadata", type: "string" }, { name: "isEncrypted", type: "bool" }],
    name: "registerIP",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "royaltyPercentage", type: "uint256" },
      { name: "duration", type: "uint256" },
      { name: "commercialUse", type: "bool" },
      { name: "terms", type: "string" },
    ],
    name: "mintLicense",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [{ name: "tokenId", type: "uint256" }], name: "payRevenue", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [{ name: "tokenId", type: "uint256" }], name: "claimRoyalties", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [{ name: "tokenId", type: "uint256" }, { name: "reason", type: "string" }],
    name: "raiseDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [], name: "registerArbitrator", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [], name: "unstake", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [{ name: "disputeId", type: "uint256" }, { name: "selectedArbitrators", type: "address[]" }],
    name: "assignArbitrators",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "disputeId", type: "uint256" }, { name: "decision", type: "bool" }, { name: "resolution", type: "string" }],
    name: "submitArbitrationDecision",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [{ name: "disputeId", type: "uint256" }], name: "checkAndResolveArbitration", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "disputeId", type: "uint256" }], name: "resolveDisputeWithoutArbitrators", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "tokenId", type: "uint256" }, { name: "to", type: "address" }], name: "transferIP", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "tokenId", type: "uint256" }], name: "getTokenDisputes", outputs: [{ name: "", type: "uint256[]" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "tokenId", type: "uint256" }], name: "hasActiveDisputes", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ name: "disputeId", type: "uint256" }],
    name: "getDispute",
    outputs: [
      { name: "disputeId_", type: "uint256" },
      { name: "tokenId_", type: "uint256" },
      { name: "disputer_", type: "address" },
      { name: "reason_", type: "string" },
      { name: "timestamp_", type: "uint256" },
      { name: "isResolved_", type: "bool" },
      { name: "arbitrationId_", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arbitrationId", type: "uint256" }],
    name: "getArbitration",
    outputs: [
      { name: "arbitrationId_", type: "uint256" },
      { name: "disputeId_", type: "uint256" },
      { name: "arbitrators_", type: "address[]" },
      { name: "votesFor_", type: "uint256" },
      { name: "votesAgainst_", type: "uint256" },
      { name: "deadline_", type: "uint256" },
      { name: "isResolved_", type: "bool" },
      { name: "resolution_", type: "string" },
      { name: "threeUpholdVotesTimestamp_", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [{ name: "arbitrator", type: "address" }], name: "getArbitratorActiveDisputes", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ name: "arbitrator", type: "address" }],
    name: "getArbitrator",
    outputs: [
      { name: "arbitrator_", type: "address" },
      { name: "stake_", type: "uint256" },
      { name: "reputation_", type: "uint256" },
      { name: "totalCases_", type: "uint256" },
      { name: "successfulCases_", type: "uint256" },
      { name: "isActive_", type: "bool" },
      { name: "registrationDate_", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "getAllArbitrators", outputs: [{ name: "", type: "address[]" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "owner", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "MIN_ARBITRATOR_STAKE", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "getActiveArbitratorsCount", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "nextDisputeId", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
] as const;
