# Workflow artifact paths for CRE CLI (--target selects section)
# Run: cre workflow simulate ip-registration-workflow --target staging-settings

staging-settings:
  user-workflow:
    workflow-name: "ip-registration-workflow-staging"
    workflow-artifacts:
      workflow-path: "./main.ts"
      config-path: "./config.staging.json"
      secrets-path: ""

production-settings:
  user-workflow:
    workflow-name: "ip-registration-workflow-production"
    workflow-artifacts:
      workflow-path: "./main.ts"
      config-path: "./config.production.json"
      secrets-path: ""
